export const ENV = {
  GRAPHQL_API_URL: import.meta.env.VITE_GRAPHQL_API_URL,
  DIRECTION_API: import.meta.env.VITE_DIRECTION_API,
  MAPBOX_ACCESS_TOKEN: import.meta.env.VITE_MAPBOX_ACCESS_TOKEN,
  GEOCODING_API: import.meta.env.VITE_DIRECTION_API,
  STRIPE_PUBLISHABLE_KEY: import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY,
  STRIPE_SECRET_KEY: import.meta.env.VITE_STRIPE_SECRET_KEY,
};
